import { INITIAL_MAX_OXYGEN } from '../constants';
import { BuildingType, GameState, ResourceType } from '../types';

export function createInitialGameState(now = Date.now()): GameState {
  return {
    resources: {
      [ResourceType.OXYGEN]: 3.8,
      [ResourceType.LUMENS]: 0,
      [ResourceType.BIOMASS]: 0,
      [ResourceType.SCRAP]: 0,
      [ResourceType.EVOLUTION]: 0,
    },
    buildings: {
      [BuildingType.PUMP]: 0,
      [BuildingType.BIO_FILTER]: 0,
      [BuildingType.NODE]: 0,
      [BuildingType.NEURAL_LINK]: 0,
      [BuildingType.COMMS_ARRAY]: 0,
    },
    flags: {
      gameStarted: false,
      hasLight: false,
      hasScavenged: false,
      inspectedJam: false,
      commsRepaired: false,
      oxygenCrisis: true,
      revealedTruth: false,
      systemBooted: true,
      crankStarted: false,
      filtersUnlocked: false,
      sonarUnlocked: false,
      impactOccurred: false,
      sosReceived: false,
      overheated: false,
      lowTempWarning: false,
      coldWeldingDiscovered: false,
      damageControlActive: false,
      furnaceUnlocked: false,
    },
    phase: 1,
    chapter1Stage: 'boot',
    logs: [],
    lastTick: now,
    totalClicks: 0,
    lastCrankTime: now - 2000,
    lastFilterTime: now - 3000,
    lastFurnaceTime: now - 4000,
    lastCollectTime: now - 6000,
    lastSonarTime: now - 8000,
    lastDiagnosticsTime: now - 10000,
    maxOxygen: INITIAL_MAX_OXYGEN,
    coreTemperature: 2,
    power: 0,
    filterWaste: 0,
    crankClicks: 0,
    furnaceUses: 0,
    sonarPings: 0,
    hullIntegrity: 100,
    damageControlTimer: 0,
  };
}
